[amqp]
source = "amqp://guest:guest@localhost:5672/"

[storage]
driver = "postgres"
source = "postgres://alex:secret@localhost:5432/calendar?sslmode=disable"

[scheduler]
checkNotificationFreqSeconds = 60
checkExpiredEventsFreqSeconds = 180
