// Code generated by sqlc. DO NOT EDIT.

package sqlcstorage

import (
	"database/sql"
	"time"
)

type Event struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	StartEvent  time.Time      `json:"start_event"`
	EndEvent    time.Time      `json:"end_event"`
	Description sql.NullString `json:"description"`
	IDUser      int64          `json:"id_user"`
}

type User struct {
	ID       int64  `json:"id"`
	Nickname string `json:"nickname"`
}
